apiVersion: argoproj.io/v1alpha1
kind: Workflow # new type of k8s spec
metadata:
  generateName: obj-detection- # name of the workflow spec
spec:
  entrypoint: obj-detection-training # invoke the hello-world template
  templates:
    - name: obj-detection-training # name of the template
      container:
        image: docker-registry.solv.local/obj_detection:latest
        command: [bash]
        args: ["start.sh"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: minio-config
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: minio-config
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                name: minio-config
                key: AWS_ENDPOINT_URL
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: minio-config
                key: AWS_REGION
        resources: # limit the resources
          limits:
            memory: 4Gi
            cpu: 2
